### ISSUE TITLE
Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by AnserBaby** [egcodes/speed-test#11]
`I/System.out: Download error...
W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:355)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
        at egcodes.com.speedtest.test.HandlerUpload.run(HttpUploadTest.java:150)`
i no changed your code ,How to repair it?

**Comment by egcodes** [comment]
Problem solved with my last commit. Can you test it again?

**Comment by rtz333** [comment]
> Problem solved with my last commit. Can you test it again?

i got same error in device HTC 10 evo android 7. But working nice on realme android 10

**Comment by rtz333** [comment]
W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    	... 26 more
I/System.out: Download error...
I/art: JIT added (osr=false) void androidx.constraintlayout.solver.widgets.Optimizer.checkMatchParent(androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer, androidx.constraintlayout.solver.LinearSystem, androidx.constraintlayout.solver.widgets.ConstraintWidget)@0x7f6d080848 ccache_size=112KB:  dcache_size=111KB: 0x7f59c145d0,0x7f59c149b8
I/art: JIT added (osr=false) boolean androidx.constraintlayout.solver.widgets.ConstraintWidget.isInVerticalChain()@0x7f6d0710a8 ccache_size=112KB:  dcache_size=111KB: 0x7f59c149e0,0x7f59c14a38
I/System.out: Download error...
I/art: JIT added (osr=false) void androidx.constraintlayout.solver.Pools$SimplePool.releaseAll(java.lang.Object[], int)@0x7f6d0759c8 ccache_size=113KB:  dcache_size=111KB: 0x7f59c14a60,0x7f59c14bd0
I/art: JIT added (osr=false) void androidx.constraintlayout.solver.LinearSystem.computeValues()@0x7f6d073cd8 ccache_size=113KB:  dcache_size=111KB: 0x7f59c14c00,0x7f59c14ca8
I/System.out: Download error...
D/dsfsafas: Upload error... 
I/System.out: Download error...
D/dsfsafas: Upload error... 
I/System.out: Download error...
D/dsfsafas: Upload error...

**Comment by andysagar** [comment]
Change HttpsURLConnection to HttpURLConnection bcz some servers are showing error with https links in HttpDownloadTest and HttpUploadTest class
