### ISSUE TITLE
Ping Test not working

### ISSUE THREAD

**Issue by tabish075** [egcodes/speed-test#8]
Hi there I have tested your app and it gives error on PingTest app do not crash but ping text is not updated here is the error:

`2019-03-25 17:04:21.300 32092-925/egcodes.com.speedtest W/System.err: java.lang.NumberFormatException: For input string: "live"
2019-03-25 17:04:21.300 32092-925/egcodes.com.speedtest W/System.err:     at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
2019-03-25 17:04:21.300 32092-925/egcodes.com.speedtest W/System.err:     at java.lang.Double.parseDouble(Double.java:547)
2019-03-25 17:04:21.300 32092-925/egcodes.com.speedtest W/System.err:     at egcodes.com.speedtest.test.PingTest.run(PingTest.java:50)
2019-03-25 17:04:21.565 32092-377/egcodes.com.speedtest I/System.out: Ping error...`

EDITED: here is how the String line data looks like

`E/line: From 192.168.12.1: icmp_seq=1 Time to live exceeded`

**Comment by sumitsonawane** [comment]
same here, any solution?

**Comment by egcodes** [comment]
Ping still may not work properly. But download and upload is working.
